### ISSUE TITLE
How did you get the volume icon widget to work?

### ISSUE THREAD

**Issue by thepenguinthatwants** [Maryll-castelino/dotfiles#1]
I've noticed that there have being some custom things added.

    spawn.easy_async("/home/maryll/.config/awesome/widgets/volume/getVolume.sh", function(stdout)
I've change that to my own path.

Is there anything else that needs to be edited?

**Comment by thepenguinthatwants** [comment]
pactl -- set-sink-volume @DEFAULT_SINK@

Wondering if the @DEFAULT_SINK@ needs to be defined somewhere else

**Comment by Maryll-castelino** [comment]
i have two separate widget templates for the volume/brightness notification and the rest of the notifications which are defined in /modules/notifications.lua, for the indicators i put the title as "indicator" to differentiate between them
```
naughty.connect_signal("request::display", function(n)

    local actions = wibox.widget {...}
    
    if n.title == "indicator" then
        naughty.layout.box {
            notification = n,
            type = "notification",
            shape = function(cr, width, height)
                gears.shape.rounded_rect(cr, width, height, 10)
            end,
            widget_template = {...}  --the widget template for the volume/brightness indicators
                
        }
    else 
        naughty.layout.box {
            notification = n,
            type = "notification",
            shape = function(cr, width, height)
                gears.shape.rounded_rect(cr, width, height, 3)
            end,
            widget_template = {...}, --the widget template for the rest of the notifications
        }
    end
    
end)
```
and while creating the notification whenever the volume is increased, decreased or toggled I pass the icon as a parameter
`local volume_icon = gears.filesystem.get_configuration_dir() .. "/widgets/volume/headphones.svg"`
```
function volume.notif()
    if volume.n and not volume.n.is_destroyed and not volume.n.is_expired then
        volume.n.message = tostring(volume.level)
    else
        volume.n = naughty.notification {
            text = tostring(volume.level),
            position = "top_left",
            icon = volume_icon,                               -- here I pass the volume icon for the notification
            font = "Open Sans Bold 15",
            title = "indicator",                                     -- here I have put the title as "indicator" to use the indicator widget template
            timeout = volume.timeout,
        }
    end
end
```

**Comment by thepenguinthatwants** [comment]
Hi,
Thanks for the answer I didn't even notice the notification.lua.


Most likely could add those stuff on other lua file. Thanks I'll try to get this work. Its really nice to get awesome to work without external programs.

**Comment by thepenguinthatwants** [comment]
Actually I still have problems.

related to notifications.lua file 57: attempt to call a nil value(field'connect_signal')

**Comment by thepenguinthatwants** [comment]
Now I've tried adding it to my theme.lua it gives 

stack traceback to 86 line 
also something related to call a nil value (field 'at _screen_connect')

86 line's block has this
```
-- Create a wibox for each screen and add it
awful.screen.connect_for_each_screen(function(s)
    s.systray = wibox.widget.systray()
    s.systray.visible = false
    beautiful.at_screen_connect(s) end)


```

**Comment by Maryll-castelino** [comment]
do you have awesome-git? maybe it's because of that.

**Comment by thepenguinthatwants** [comment]
Hmm, I've normally installed awesome and few aur packages when needed. I'll try to switch to awesome-git

**Comment by thepenguinthatwants** [comment]
Okay after installing awesome-git it doesnt give errors. But it also doesnt seem to give the icon notification

**Comment by Maryll-castelino** [comment]
did you add these keys to the global keybindings?
```
local volume = require("widgets.volume.volume")
```
```
awful.keyboard.append_global_keybindings({
    -- keyboard volume keys
    awful.key({}, 'XF86AudioRaiseVolume', 
        function() 
            volume.inc() 
        end, 
        {description = 'volume up', group = 'hotkeys'}),
    awful.key({}, 'XF86AudioLowerVolume', 
        function() 
            volume.dec() 
        end, 
        {description = 'volume down', group = 'hotkeys'}),
    awful.key({}, 'XF86AudioMute', 
        function() 
            volume.toggle() 
        end, 
        {description = 'toggle mute', group = 'hotkeys'}),
})
```

**Comment by thepenguinthatwants** [comment]
Yeah those were added.. I skipped the toggle mute tho, as I didn't need that.

Wondering if changing this pactl -- set-sink-volume @DEFAULT_SINK@ out to

`    _spawn.with_shell('amixer -D pulse sset Master 15%+ ' .. tostring(volume.level) .. '%')_`
broke the functionality for the icons.

**Comment by Maryll-castelino** [comment]
did you copy the headphones svg icon to the folder? maybe you need to change the path of the icon

**Comment by thepenguinthatwants** [comment]
Yeah the icon is in that location. 
I copied this whole folder https://github.com/Maryll-castelino/dotfiles/tree/master/widgets/volume to my widgets/volume.

The whole notification the numbers etc nothing is showing up.

**Comment by Maryll-castelino** [comment]
just upload you config to github and send me a link. I'll be able to find the error faster that way.
